### ISSUE TITLE
[mattermost-team-edition] read only file system on start up

### ISSUE THREAD

**Issue by mehdouch77** [mattermost/mattermost-helm#100]
While installing the mattermost team edition helm chart on my GKE for the first time, i got a read only file system error without modifying anything : 

**Error message :** 

{"level":"error","ts":1563295457.9649801,"caller":"app/config.go:54","msg":"Failed to update config","error":"failed to persist: failed to write file: open /mattermost/config/config.json: read-only file system","errorVerbose":"open /mattermost/config/config.json: read-only file system

**My values.yaml file : **

# Image tag
image:
  tag: 5.12.1
# Persistense for mattermost
persistence:
  data:
    enabled: true
    size: 20Gi
    storageClass: standard
    accessMode: ReadWriteOnce

# Ingress params to access the cluster from outside
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: XXX
  hosts:
    - XXX
  tls:
    - secretName: XXX-tls
      hosts:
        - XXX

# Mysql Params
mysql:
  enabled: true
  mysqlRootPassword: "Password"
  mysqlUser: "USer"
  mysqlPassword: "Password"
  mysqlDatabase: db_name

  repository: mysql
  tag: 5.7
  imagePullPolicy: IfNotPresent

  persistence:
    enabled: true
    storageClass: standard
    accessMode: ReadWriteOnce
    size: 10Gi

# Config File for mattermost
configJSON: {
  "ServiceSettings": {
    "SiteURL": "XXXX",
    "GoogleDeveloperKey": "XXXXX",
    "EnablePostUsernameOverride": true,
    "EnablePostIconOverride": true,
    "EnableLinkPreviews": true,
  },
  "TeamSettings": {
    "SiteName": "XXX",
    "EnableCustomBrand": true,
  },
  "EmailSettings": {
    "SendEmailNotifications": true,
    "RequireEmailVerification": true,
    "SMTPUsername": "XXX",
    "SMTPPassword": "XXX",
    "EnableSMTPAuth": true,
    "SMTPServer": "XXX",
    "SMTPPort": "587",
    "ConnectionSecurity": "STARTTLS",
    "EnableEmailBatching": true,
  },
  "PluginSettings": {
    "Enable": true,
    "EnableUploads": true,
  }
}

**Comment by ywang146** [comment]
Same issue
│ {"level":"info","ts":1565862568.4581082,"caller":"app/server.go:216","msg":"Current working directory is /mattermost"}                                                                                                                                                          │ {"level":"info","ts":1565862568.4581385,"caller":"app/server.go:217","msg":"Loaded config","source":"file:///mattermost/config/config.json"}                                                                                                                                    │ {"level":"error","ts":1565862568.462423,"caller":"app/config.go:54","msg":"Failed to update config","error":"failed to persist: failed to write file: open /mattermost/config/config.json: read-only file system","errorVerbose":"open /mattermost/config/config.json: read-on  │ ly file system\nfailed to write file\ngithub.com/mattermost/mattermost-server/config.(*FileStore).persist\n\t/go/src/github.com/mattermost/mattermost-server/config/file.go:117\ngithub.com/mattermost/mattermost-server/config.(*commonStore).set\n\t/go/src/github.com/matte  │ rmost/mattermost-server/config/common.go:72\ngithub.com/mattermost/mattermost-server/config.(*FileStore).Set\n\t/go/src/github.com/mattermost/mattermost-server/config/file.go:97\ngithub.com/mattermost/mattermost-server/app.(*Server).UpdateConfig\n\t/go/src/github.com/ma  │ ttermost/mattermost-server/app/config.go:53\ngithub.com/mattermost/mattermost-server/app.NewServer\n\t/go/src/github.com/mattermost/mattermost-server/app/server.go:229\ngithub.com/mattermost/mattermost-server/cmd/mattermost/commands.runServer\n\t/go/src/github.com/matte  │ rmost/mattermost-server/cmd/mattermost/commands/server.go:64\ngithub.com/mattermost/mattermost-server/cmd/mattermost/commands.serverCmdF\n\t/go/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/server.go:53\ngithub.com/mattermost/mattermost-server/vend  │ or/github.com/spf13/cobra.(*Command).execute\n\t/go/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:762\ngithub.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/go/src/github.com/mattermost/matte  │ rmost-server/vendor/github.com/spf13/cobra/command.go:852\ngithub.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/go/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:800\ngithub.com/mattermost/mat  │ termost-server/cmd/mattermost/commands.Run\n\t/go/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/root.go:15\nmain.main\n\t/go/src/github.com/mattermost/mattermost-server/cmd/mattermost/main.go:30\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:20  │ 0\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337\nfailed to persist\ngithub.com/mattermost/mattermost-server/config.(*commonStore).set\n\t/go/src/github.com/mattermost/mattermost-server/config/common.go:73\ngithub.com/mattermost/mattermost-server/config.(  │ *FileStore).Set\n\t/go/src/github.com/mattermost/mattermost-server/config/file.go:97\ngithub.com/mattermost/mattermost-server/app.(*Server).UpdateConfig\n\t/go/src/github.com/mattermost/mattermost-server/app/config.go:53\ngithub.com/mattermost/mattermost-server/app.NewS  │ erver\n\t/go/src/github.com/mattermost/mattermost-server/app/server.go:229\ngithub.com/mattermost/mattermost-server/cmd/mattermost/commands.runServer\n\t/go/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/server.go:64\ngithub.com/mattermost/mattermos  │ t-server/cmd/mattermost/commands.serverCmdF\n\t/go/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/server.go:53\ngithub.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).execute\n\t/go/src/github.com/mattermost/mattermost-serv  │ er/vendor/github.com/spf13/cobra/command.go:762\ngithub.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/go/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:852\ngithub.com/mattermost/mattermost-s  │ erver/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/go/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:800\ngithub.com/mattermost/mattermost-server/cmd/mattermost/commands.Run\n\t/go/src/github.com/mattermost/mattermost-server  │ /cmd/mattermost/commands/root.go:15\nmain.main\n\t/go/src/github.com/mattermost/mattermost-server/cmd/mattermost/main.go:30\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337"}                              │ {"level":"info","ts":1565862568.5106914,"caller":"mlog/sugar.go:19","msg":"Scheduling next survey for Sep 5, 2019","plugin_id":"com.mattermost.nps"}

**Comment by ywang146** [comment]
│ {"level":"info","ts":1565862568.4581082,"caller":"app/server.go:216","msg":"Current working directory is /mattermost"}                                                                                                                                                          │ {"level":"info","ts":1565862568.4581385,"caller":"app/server.go:217","msg":"Loaded config","source":"file:///mattermost/config/config.json"}                                                                                                                                    │ {"level":"error","ts":1565862568.462423,"caller":"app/config.go:54","msg":"Failed to update config","error":"failed to persist: failed to write file: open /mattermost/config/config.json: read-only file system","errorVerbose":"open /mattermost/config/config.json: read-on  │ ly file system\nfailed to write file\ngithub.com/mattermost/mattermost-server/config.(*FileStore).persist\n\t/go/src/github.com/mattermost/mattermost-server/config/file.go:117\ngithub.com/mattermost/mattermost-server/config.(*commonStore).set\n\t/go/src/github.com/matte  │ rmost/mattermost-server/config/common.go:72\ngithub.com/mattermost/mattermost-server/config.(*FileStore).Set\n\t/go/src/github.com/mattermost/mattermost-server/config/file.go:97\ngithub.com/mattermost/mattermost-server/app.(*Server).UpdateConfig\n\t/go/src/github.com/ma  │ ttermost/mattermost-server/app/config.go:53\ngithub.com/mattermost/mattermost-server/app.NewServer\n\t/go/src/github.com/mattermost/mattermost-server/app/server.go:229\ngithub.com/mattermost/mattermost-server/cmd/mattermost/commands.runServer\n\t/go/src/github.com/matte  │ rmost/mattermost-server/cmd/mattermost/commands/server.go:64\ngithub.com/mattermost/mattermost-server/cmd/mattermost/commands.serverCmdF\n\t/go/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/server.go:53\ngithub.com/mattermost/mattermost-server/vend  │ or/github.com/spf13/cobra.(*Command).execute\n\t/go/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:762\ngithub.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/go/src/github.com/mattermost/matte  │ rmost-server/vendor/github.com/spf13/cobra/command.go:852\ngithub.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/go/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:800\ngithub.com/mattermost/mat  │ termost-server/cmd/mattermost/commands.Run\n\t/go/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/root.go:15\nmain.main\n\t/go/src/github.com/mattermost/mattermost-server/cmd/mattermost/main.go:30\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:20  │ 0\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337\nfailed to persist\ngithub.com/mattermost/mattermost-server/config.(*commonStore).set\n\t/go/src/github.com/mattermost/mattermost-server/config/common.go:73\ngithub.com/mattermost/mattermost-server/config.(  │ *FileStore).Set\n\t/go/src/github.com/mattermost/mattermost-server/config/file.go:97\ngithub.com/mattermost/mattermost-server/app.(*Server).UpdateConfig\n\t/go/src/github.com/mattermost/mattermost-server/app/config.go:53\ngithub.com/mattermost/mattermost-server/app.NewS  │ erver\n\t/go/src/github.com/mattermost/mattermost-server/app/server.go:229\ngithub.com/mattermost/mattermost-server/cmd/mattermost/commands.runServer\n\t/go/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/server.go:64\ngithub.com/mattermost/mattermos  │ t-server/cmd/mattermost/commands.serverCmdF\n\t/go/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/server.go:53\ngithub.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).execute\n\t/go/src/github.com/mattermost/mattermost-serv  │ er/vendor/github.com/spf13/cobra/command.go:762\ngithub.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/go/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:852\ngithub.com/mattermost/mattermost-s  │ erver/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/go/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:800\ngithub.com/mattermost/mattermost-server/cmd/mattermost/commands.Run\n\t/go/src/github.com/mattermost/mattermost-server  │ /cmd/mattermost/commands/root.go:15\nmain.main\n\t/go/src/github.com/mattermost/mattermost-server/cmd/mattermost/main.go:30\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337"}                              │ {"level":"info","ts":1565862568.5106914,"caller":"mlog/sugar.go:19","msg":"Scheduling next survey for Sep 5, 2019","plugin_id":"com.mattermost.nps"}

**Comment by yekibud** [comment]
Same issue.  @mehdouch77 @ywang146 have you figured this out?  Any help Mattermost folks?

**Comment by kiov** [comment]
The problem is that /mattermost/config/config.json is mounted from a secret and is read only.
My workarround was create a new volume for /mattermost/config and create a config.json inside it. 
With that I could change the configs on the admin UI,

**Comment by simonxlh** [comment]
@kiov  Can you show me your deployment. yaml?
I tried to remounted config. json, but it never started properly. thanks（15215796876@163.com）

**Comment by rsp9u** [comment]
Same issue. I added below settings to values.yaml, and then it works.

Note that config.json is perhaps able to be changed on the admin UI, but it would be overwritten when the pod restarts.  
Also note that it's insecure because the tokens in config.json are put into the persistent volume.

```yaml
extraInitContainers:
  - name: copy-config
    image: "alpine:latest"
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /mattermost/config/config.json
      name: config-json
      subPath: config.json
    - mountPath: /mattermost/data
      name: mattermost-data
    command: ["/bin/ash", "-c", "cp -f /mattermost/config/config.json /mattermost/data/config.json"]
extraEnvVars:
  - name: MM_CONFIG
    value: "/mattermost/data/config.json"
```

**Comment by simonxlh** [comment]
> Same issue. I added below settings to values.yaml, and then it works.
> 
> Note that config.json is perhaps able to be changed on the admin UI, but it would be overwritten when the pod restarts.
> Also note that it's insecure because the tokens in config.json are put into the persistent volume.
> 
> ```yaml
> extraInitContainers:
>   - name: copy-config
>     image: "alpine:latest"
>     imagePullPolicy: IfNotPresent
>     volumeMounts:
>     - mountPath: /mattermost/config/config.json
>       name: config-json
>       subPath: config.json
>     - mountPath: /mattermost/data
>       name: mattermost-data
>     command: ["/bin/ash", "-c", "cp -f /mattermost/config/config.json /mattermost/data/config.json"]
> extraEnvVars:
>   - name: MM_CONFIG
>     value: "/mattermost/data/config.json"
> ```

I will determine whether to copy according to whether there is a config.json file in the folder `/mattermost/data/`.
This may temporarily solve the coverage problem  when the pod restarts.
```yaml
    command: ["/bin/ash", "-c", "if [[ ! -f \"/mattermost/data/config.json\" ]] ;then echo \"copy configJSON\"; cp -f /mattermost/config/config.json /mattermost/data/config.json;else echo \"configJSON exist\"; fi;"]
```

**Comment by masterkain** [comment]
```
    extraInitContainers:
    - name: copy-config
      image: "alpine:latest"
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /mattermost/config/config.json
        name: config-json
        subPath: config.json
      - mountPath: /mattermost/data
        name: mattermost-data
      command: ["/bin/ash", "-c", "if [[ ! -f \"/mattermost/data/config.json\" ]] ;then echo \"copy configJSON\"; cp -f /mattermost/config/config.json /mattermost/data/config.json;else echo \"configJSON exist\"; fi;"]
    extraEnvVars:
      - name: MM_CONFIG
        value: "/mattermost/data/config.json"
```

```
 {"level":"info","ts":1581544225.523905,"caller":"app/server.go:222","msg":"Loaded config","source":"file:///mattermost/data/config.json"}
│ {"level":"error","ts":1581544225.5526595,"caller":"app/config.go:54","msg":"Failed to update config","error":"failed to persist: failed to write file: open /mattermost/data/config.json: permission denied","errorVerbose":"open /mattermost/data/config.json: permission denied\nf
```

is the proposed solution working for you?

**Comment by simonxlh** [comment]
@masterkain I haven't encountered such an error. Maybe you should check permissions in directory`/mattermost/data` . And `persistence.data.accessMode` in `values.yaml`

**Comment by kissi7** [comment]
> ```
>     extraInitContainers:
>     - name: copy-config
>       image: "alpine:latest"
>       imagePullPolicy: IfNotPresent
>       volumeMounts:
>       - mountPath: /mattermost/config/config.json
>         name: config-json
>         subPath: config.json
>       - mountPath: /mattermost/data
>         name: mattermost-data
>       command: ["/bin/ash", "-c", "if [[ ! -f \"/mattermost/data/config.json\" ]] ;then echo \"copy configJSON\"; cp -f /mattermost/config/config.json /mattermost/data/config.json;else echo \"configJSON exist\"; fi;"]
>     extraEnvVars:
>       - name: MM_CONFIG
>         value: "/mattermost/data/config.json"
> ```
> 
> 
> ```
>  {"level":"info","ts":1581544225.523905,"caller":"app/server.go:222","msg":"Loaded config","source":"file:///mattermost/data/config.json"}
> │ {"level":"error","ts":1581544225.5526595,"caller":"app/config.go:54","msg":"Failed to update config","error":"failed to persist: failed to write file: open /mattermost/data/config.json: permission denied","errorVerbose":"open /mattermost/data/config.json: permission denied\nf
> ```
> 
> 
> is the proposed solution working for you?

Hi, are you using the "old" version 5.13.2? The latest one is not run under the root but unter the mattermost user (2000:2000) and default persistenVolume mount permission are root:root

**Comment by masterkain** [comment]
@simonxlh @kissi7 I think I'm using release-5.17, will try adjusting for the new mattermost user, thanks for the hints

**Comment by mrvnklm** [comment]
To make the above work with the latest version, change the command to set file owner like so:
`    command: ["/bin/ash", "-c", "if [[ ! -f \"/mattermost/data/config.json\" ]] ;then echo \"copy configJSON\"; cp -f /mattermost/config/config.json /mattermost/data/config.json && chown 2000:2000 /mattermost/data/config.json;else echo \"configJSON exist\"; fi;"]`

**Comment by verovan** [comment]
Any updates on this?

**Comment by masterkain** [comment]
using `mattermost/mattermost-team-edition:5.31.0` I can't start the pod. tested some `command` as you can be see below with the same results.

```
│ Error: failed to load configuration: failed to create store: unable to load on store creation: failed to persist: failed to write file: open /mattermost/data/config.json: permission denied
```

```
    extraInitContainers:
    - name: copy-config
      image: "alpine:latest"
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /mattermost/config/config.json
        name: config-json
        subPath: config.json
      - mountPath: /mattermost/data
        name: mattermost-data
      # command: ["/bin/ash", "-c", "if [[ ! -f \"/mattermost/data/config.json\" ]] ;then echo \"copy configJSON\"; cp -f /mattermost/config/config.json /mattermost/data/config.json;else echo \"configJSON exist\"; fi; chown 2000:2000 /mattermost/data/config.json; chgrp 2000 /mattermost/data/config.json; "]
      command: ["/bin/ash", "-c", "if [[ ! -f \"/mattermost/data/config.json\" ]] ;then echo \"copy configJSON\"; cp -f /mattermost/config/config.json /mattermost/data/config.json && chown 2000:2000 /mattermost/data/config.json;else echo \"configJSON exist\"; fi;"]
      # command: ["/bin/ash", "-c", "cp -f /mattermost/config/config.json /mattermost/data/config.json"]
    extraEnvVars:
      - name: MM_CONFIG
        value: "/mattermost/data/config.json"
```

any hint?

**Comment by rrey** [comment]
Here is the config change to do to have it working:
```
extraEnvVars:
  - name: MM_CONFIG
    value: "/mattermost/data/config.json"

extraInitContainers:
  - name: copy-config
    image: "alpine:latest"
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /mattermost/config/config.json
      name: config-json
      subPath: config.json
    - mountPath: /mattermost/data
      name: mattermost-data
    command: ["/bin/ash", "-c", "if [[ ! -f \"/mattermost/data/config.json\" ]] ;then echo \"copy configJSON\"; cp -f /mattermost/config/config.json /mattermost/data/config.json && chown 2000:2000 /mattermost/data/config.json;else echo \"configJSON exist\"; fi;"]
```

Nothing new from previous posts, just gathered the solutions provided.

It is a hack though, and the chart needs a fix to have 5.30+ working out of the box. (wink wink maintainers <3)
