### ISSUE TITLE
Profile uploads will fail due to permissions issue on /mattermmost/data

### ISSUE THREAD

**Issue by nsteinmetz** [mattermost/mattermost-helm#114]
Hello,

The PVC is mounted with root permissions and not mattermost user ones. As a consequence, uploads for pictures profils will fails as it can't create `/mattermost/data/users`

```
kubectl exec -ti zooming-saola-mattermost-team-edition-7f6c9ff6dd-sw99s -- ls -al /mattermost/ |grep data
drwxr-xr-x    3 root     root          4096 Sep 19 20:11 data
```

How can I fix this permission issue as I can't chown files and sudo is not present either.

**Comment by nsteinmetz** [comment]
Ok found it - add in `values.yml`:

```
extraInitContainers:
  - name: volume-mount-hack
    image: busybox
    command: ["sh", "-c", "chown -R 2000:2000 /mattermost/data"]
    volumeMounts:
    - name: mattermost-data
      mountPath: /mattermost/data
```

Shouldn't it be present by default if persistence is enabled ?
