### ISSUE TITLE
Allow additional persistence mounts

### ISSUE THREAD

**Issue by devonwarren** [mattermost/mattermost-helm#124]
We have a local CA that is needed to be imported into the deployment in order for Jira integration to be supported. We got around this in Jenkins via just defining an addition mount in /etc/ssl/certs/ with the **persistence.mounts** and **persistence.volumes** options.

Without this setup we get the output below on doing a **/jira connect**, let me know if there is a better way to do things

> failed to get a connect link: Post https://jira/plugins/servlet/oauth/request-token: x509: certificate signed by unknown authority

For reference on Jenkins implementation- https://github.com/helm/charts/blob/master/stable/jenkins/templates/jenkins-master-deployment.yaml#L233

**Comment by pascalrimann** [comment]
How can i add with the extraVolumes CA certificates and run update-ca-certificates?

I have added them with this block (secret in the Namespace before):
```
extraVolumes:
  - name: custom-ca
    secret:
      secretName: custom-ca
extraVolumeMounts: 
  - name: custom-ca
    mountPath: "/usr/local/share/ca-certificates"
```
when i want to run update-ca-certificates afterwards i get this error:
```
Failed to open temporary file /etc/ssl/certs/bundleXXXXXX for ca bundle
```
