### ISSUE TITLE
Liveness probe and readiness probe fail

### ISSUE THREAD

**Issue by verovan** [mattermost/mattermost-helm#199]
I deployed the team edition with Argocd (helm), version 3.19.0, in IBM cloud. All resources were provisioned, database is up but the server never starts.
```
Events:
  Type     Reason            Age                   From                    Message
  ----     ------            ----                  ----                    -------
  Warning  FailedScheduling  18m (x4 over 19m)     default-scheduler       0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled         18m                   default-scheduler       Successfully assigned mattermost/mattermost-mattermost-team-edition-5c56645b99-fj65m to 10.150.188.36
  Normal   Pulled            17m                   kubelet, 10.150.188.36  Container image "appropriate/curl:latest" already present on machine
  Normal   Created           17m                   kubelet, 10.150.188.36  Created container init-mysql
  Normal   Started           17m                   kubelet, 10.150.188.36  Started container init-mysql
  Normal   Pulled            12m (x2 over 14m)     kubelet, 10.150.188.36  Container image "mattermost/mattermost-team-edition:5.29.0" already present on machine
  Normal   Created           12m (x2 over 14m)     kubelet, 10.150.188.36  Created container mattermost-team-edition
  Normal   Started           12m (x2 over 14m)     kubelet, 10.150.188.36  Started container mattermost-team-edition
  Warning  Unhealthy         12m (x3 over 13m)     kubelet, 10.150.188.36  Liveness probe failed: Get http://172.30.3.19:8065/api/v4/system/ping: dial tcp 172.30.3.19:8065: connect: connection refused
  Normal   Killing           12m                   kubelet, 10.150.188.36  Container mattermost-team-edition failed liveness probe, will be restarted
  Warning  Unhealthy         2m16s (x44 over 14m)  kubelet, 10.150.188.36  Readiness probe failed: Get http://172.30.3.19:8065/api/v4/system/ping: dial tcp 172.30.3.19:8065: connect: connection refused
```
Values are as follow:
```
        persistence:
          data:
            storageClass: "ibmc-block-silver"
          plugins:
            storageClass: "ibmc-block-silver"
        mysql:
          mysqlRootPassword: "change-me-please"
          mysqlUser: "administrator"
          mysqlPassword: "super-secret"
          persistence:
            storageClass: "ibmc-block-silver"
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            kubernetes.io/ingress.class: nginx
            kubernetes.io/tls-acme: "true"
          hosts:
            - chat.example.com
          tls:
            - secretName: chat.example.com-secret
              hosts:
                - chat.example.com
        configJSON:
          ServiceSettings:
            SiteURL: "https://chat.example.com"
            EnableCustomEmoji: true
            EnableLinkPreviews: true
            SessionLengthWebInDays: 15
            SessionLengthMobileInDays: 15
          TeamSettings:
            SiteName: "Team Chat"
          PasswordSettings:
            MinimumLength: 8
```
