### ISSUE TITLE
[mattermost-team-edition] read only file system ONLY FOR >=5.30

### ISSUE THREAD

**Issue by r3kzi** [mattermost/mattermost-helm#203]
When i run mattermost images >= 5.30 mattermost wont start due to `Error: failed to load configuration: failed to create store: unable to load on store creation: failed to persist: failed to write file: open /mattermost/config/config.json: read-only file system`

```
image:
  repository: mattermost/mattermost-team-edition
  tag: 5.31.0-rc2
  imagePullPolicy: IfNotPresent
```

When i switch to older versions like **5.29.1** mattermost will start.
