### ISSUE TITLE
Issues upgrading to MM-TE 5 chart

### ISSUE THREAD

**Issue by JosefWN** [mattermost/mattermost-helm#231]
Hello, I have followed the instructions when upgrading from MM-TE 4 to 5, but gotten stuck:

```
cp config/config.json /tmp
```
```
~ $ ./bin/mattermost config migrate /tmp/config-mm.json "mysql://mmuser:mmuser123@tcp(mm-te-mysql:3306)/mattermost?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s"
```

`/tmp/config-mm.json` seems to be a generic config file, not the one I am actually using, typo in the upgrade instructions? Should it not be `./bin/mattermost config migrate /tmp/config.json ...`?

I'm now getting (on Mattermost `5.29.0` with the 5.0 chart):

```
Error: failed to load configuration: failed to initialize: failed to create Configurations table: dial tcp: lookup postgres on 10.152.183.10:53: no such host
````

Notably, my database server's DNS is not `postgres`.

Any advise on how to proceed would be much appreciated! 🙂

EDIT: Just to clarify, I also use postgres, like @xtermi2.

**Comment by xtermi2** [comment]
I have the same issue, but I use postgres but same error in step 6 in the migration guide:
```
Error: failed to load configuration: failed to initialize: failed to create Configurations table: dial tcp: lookup postgres on 172.20.0.10:53: no such host
```
I set the database in my `helm-values.yaml` like this:
```yaml
mysql:
  enabled: false
externalDB:
  enabled: true
  externalDriverType: "postgres"
```
and set the `externalConnectionString` as parameter in helm cmd like this
```bash
helm upgrade --namespace my-namespace --install mattermost -f helm-values.yaml mattermost/mattermost-team-edition --version 5.1.1 \
		--set externalDB.externalConnectionString="postgres://mattermost:<my-password>@<some_name>.eu-central-1.rds.amazonaws.com:5432/mattermost?sslmode=require&connect_timeout=10"
```

**Comment by masterkain** [comment]
I have the same issue with postgres, I can't run mattermost atm, any solution?

**Comment by xtermi2** [comment]
> I have the same issue with postgres, I can't run mattermost atm, any solution?

This workaround with chart 4.0.0 worker for us: https://github.com/mattermost/mattermost-helm/issues/100#issuecomment-848626644

This workaround looks for me even better than persisting the config in the database, because I can control via helm the default properties and can overwride the config like this:
```yaml
extraEnvVars:
  - name: MM_CONFIG
    value: "/mattermost/data/config.json"

extraInitContainers:
  - name: copy-config
    image: "alpine:latest"
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /mattermost/config/config.json
        name: config-json
        subPath: config.json
      - mountPath: /mattermost/data
        name: mattermost-data
    command: ["/bin/ash", "-c", "echo \"copy configJSON\"; cp -f /mattermost/config/config.json /mattermost/data/config.json && chown 2000:2000 /mattermost/data/config.json;"]
```
This will overwride the config on every pod start
