### ISSUE TITLE
configJSON is not working as per readme

### ISSUE THREAD

**Issue by wael-sadek** [mattermost/mattermost-helm#238]
Trying to set the siteurl as per readme doesn't work:
```
configJSON:
  ServiceSettings:
    SiteURL: "https://mattermost.example.com"
```
The work around is to set it via extraEnvVars MM_SERVICESETTINGS_SITEURL.

**Comment by cpanato** [comment]
thanks for the catch.
the readme needs to be updated.

Are you willing to open a PR and make this change? thanks!

**Comment by cpanato** [comment]
@mike-code this is the pattern to have environment variables for the config, this looks correct

**Comment by Julchencita** [comment]
@cpanato Do I understand correctly that using environment variables is now the only way to set anything that was previously configured like this
````
configJSON:
  ServiceSettings:
    SiteURL: "https://mattermost.example.com"
  TeamSettings:
    SiteName: "Mattermost on Example.com"
```` 
And that the mattermost/config folder inside the pod is now supposed to be empty?
