### ISSUE TITLE
Websocket error

### ISSUE THREAD

**Issue by cneumaier** [mattermost/mattermost-helm#319]
Hello everybody,

i am trying to install the mattermost team edition chart on my cluster but I am running into some websocket issues.
I am experiencing the same issues as described [here](https://forum.mattermost.com/t/websocket-connect-err-error-websocket-the-client-is-not-using-the-websocket-protocol-upgrade-token-not-found-in-connection/9110/4).

Is this an issue of the helm chart, the docker container or the nginx ingress?

`{"timestamp":"2022-03-31 21:10:41.886 Z","level":"error","msg":"Failed to upgrade websocket connection.","caller":"web/context.go:105","path":"/api/v4/websocket","request_id":"a1us537gp3b7xxyoawiuksyrmr","ip_addr":"xxxxx","user_id":"xxxxxx","method":"GET","err_where":"connect","http_code":500,"err_details":"websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header"}
`

UPDATE: 
Please keep in mind that I am on kubernetes version _1.23.1_ and i am therefore using the _networking.k8s.io/v1_ ingress api. I am not sure this issue is related to that. I made the same changes to the ingress as described in #250. Everything else is working as expected. 
____________________________________
Kubernetes version: v1.23.1
Ingress: Nginx
Ingress apiVersion: networking.k8s.io/v1

**Comment by cneumaier** [comment]
Is this related to #280?

**Comment by agnivade** [comment]
@gabrieljackson / @Szymongib - Any thoughts on this? It looks like the nginx config isn't upgrading the websocket connection.

**Comment by Szymongib** [comment]
> and i am therefore using the networking.k8s.io/v1 ingress api

Do you create the ingress manually then? Could you share it here so we can investigate?

**Comment by cneumaier** [comment]
I cloned the repo and changed the ingress definition inside the helm chart (team-edition).
Here is the resulting ingress definition:

```
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: mattermost-mattermost-team-edition
  namespace: gitlab
  labels:
    app.kubernetes.io/instance: mattermost
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mattermost-team-edition
    helm.sh/chart: mattermost-team-edition-6.4.1
  annotations:
    acme.cert-manager.io/http01-edit-in-place: 'true'
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    meta.helm.sh/release-name: mattermost
    meta.helm.sh/release-namespace: gitlab
    nginx.ingress.kubernetes.io/client-max-body-size: 1G
    nginx.ingress.kubernetes.io/proxy-body-size: 1G 
spec:
  tls:
    - hosts:
        - mattermost.domain.com
      secretName: secret-name
  rules:
    - host: mattermost.domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mattermost-team-edition
                port:
                  number: 8065
status:
  loadBalancer: {}
```

After several failed attempts i also tried to add a second ingress especially for the upgrade of the connection:

```
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: mattermost-mattermost-team-edition-header
  namespace: gitlab
  labels:
    app.kubernetes.io/instance: mattermost
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mattermost-team-edition
    helm.sh/chart: mattermost-team-edition-6.4.1
  annotations:
    acme.cert-manager.io/http01-edit-in-place: 'true'
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    meta.helm.sh/release-name: mattermost
    meta.helm.sh/release-namespace: gitlab
    nginx.ingress.kubernetes.io/client-max-body-size: 1G
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Upgrade: $http_upgrade";
      more_set_headers "Connection: 'upgrade'";
      proxy_set_header "Upgrade: $http_upgrade";
      proxy_set_header "Connection: 'upgrade'";
    nginx.ingress.kubernetes.io/proxy-body-size: 1G
spec:
  tls:
    - hosts:
        - mattermost.domain.com
      secretName: secret-name
  rules:
    - host: mattermost.domain.com
      http:
        paths:
          - path: /api/v[0-9]+/(users/)?websocket$
            pathType: Prefix
            backend:
              service:
                name: mattermost-team-edition
                port:
                  number: 8065
status:
  loadBalancer: {}
```
