### ISSUE TITLE
[focalboard] Ingress missing ingressClassName

### ISSUE THREAD

**Issue by maxirus** [mattermost/mattermost-helm#337]
With `networking.k8s.io/v1`, the Class.Spec expects the attribute `ingressClassName`.

Example:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
#...
spec:
  ingressClassName: nginx
```

`ingressClassName` should be configurable via `.Values`
