### ISSUE TITLE
RTCD: Custom CA with volume mount

### ISSUE THREAD

**Issue by patatman** [mattermost/mattermost-helm#375]
We're using a Custom CA and would like the ability to use Certificates signed by our own CA.
This means mounting a additional volume to the Daemonset, and making sure it trusts certificates handed out by the internal CA.

Typically the custom CA gets mounted in `/etc/ssl/certs/`

The current Chart for RTCD doesn't seem to allow for custom mounts. 

For our Mattermost install we use: 
```
VolumeMounts:
    - name: ca
      mountPath: /etc/ssl/certs/ca.crt
      subPath: ca.crt
volumes:
  - name: ca
    secret:
      secretName: ca
```
