### ISSUE TITLE
[mattermost-enterprise-edition] Allow existing config.json 

### ISSUE THREAD

**Issue by Moep90** [mattermost/mattermost-helm#415]
Allow to use an existingConfigJson instead of the predefined tmpl or alternativly allow to configure every section with defaults.
like:
```yaml
global:
  TeamSettings:
    enableTeamCreation: true
    enableUserCreation: true
    enableOpenServer: true
  ServiceSettings:
    enableLinkPreviews: true
    enableCustomEmoji: true
```
