### ISSUE TITLE
Chart behavior changed regarding global.features.database.existingDatabaseSecret in latest helm versions

### ISSUE THREAD

**Issue by hdeadman** [mattermost/mattermost-helm#425]
Running with recent release of  helm 3.13.1 the output for MM_CONFIG env variable is bad:
`helm template -name mattermost mattermost/mattermost-enterprise-edition`
```
        - name: MM_CONFIG
          valueFrom:
            secretKeyRef:
              name:
              key:
```

Running with helm 3.9.0 you get the intended output:
`helm390 template -name mattermost mattermost/mattermost-enterprise-edition`
```
        - name: MM_CONFIG
          valueFrom:
            secretKeyRef:
              name: mattermost-mattermost-enterprise-edition-mattermost-dbsecret
              key: mattermost.dbsecret
```

From the deployment app template:
```
{{- if .Values.global.features.database.existingDatabaseSecret }}
  name: {{ .Values.global.features.database.existingDatabaseSecret.name }}
  key: {{ .Values.global.features.database.existingDatabaseSecret.key }}
{{- else }}
  name: {{ include "mattermost-enterprise-edition.fullname" . }}-mattermost-dbsecret
  key: mattermost.dbsecret
{{- end }}
```

From the values.yaml
```
global:
  features:
    database:

      existingDatabaseSecret:
        name:
        key:
```

It seems like the latest version of helm doesn't treat the `existingDatabaseSecret` map with two blank keys as "false". 

The values.yaml should probably be changed to:
```
      existingDatabaseSecret: {}
#        name:
#        key:
```
