### ISSUE TITLE
[mattermost-enterprise-edition] Mistake in the mysqlha helm chart

### ISSUE THREAD

**Issue by Towarmat83** [mattermost/mattermost-helm#483]
Hello, I would like to use your mattermost enterprise edition for my self hosted instance.

To do that, I'm using your helm chart according this link : https://helm.mattermost.com/index.yaml
I'm using this link so I can download automatically each new release. 

With that, I have access to the .tgz however, I notice a mistake in each version of mattermost enterprise edition.

I already use the team-edition with this mechanism and it works very well. Only the entreprise edition is concerned. 

This mistake is in the mysqlha repository (charts/mysqlha/statefulset.yaml).

In this file, there is a double "selector" giving me a error to correctly apply your chart. 

```yaml
spec:
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      release: {{ .Release.Name }}
  serviceName: {{ template "fullname" . }}
  replicas: {{ .Values.mysqlha.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
```

The second "selector" is duplicated. 

I can't do a pull request because the actual github repository isn't the .tgz but the .zip available in the Release page.
