### ISSUE TITLE
externalDB doesn't allow different components to be read from values

### ISSUE THREAD

**Issue by jonathanmccracken** [mattermost/mattermost-helm#487]
Ideally we can set each component of the connection string allowing to read these from configmaps/secrets in k8s.

eg
`
externalDB:
   dbUsername: "foo"
   dbPassword:  "bar" # or fromExternalSecret
   ....
`
Alternatively these could also reference an external secret like many other helm charts - 
https://github.com/immich-app/immich-charts/blob/4b3e1d4d0b15a30db33bc76fb847b89d0f8bd6f0/charts/immich/values.yaml#L12

**Relevant lines:**
https://github.com/mattermost/mattermost-helm/blob/0ce91320ff8ec9f79ae07bc64ea700553cc811f2/charts/mattermost-team-edition/values.yaml#L94C1-L96C30

**Comment by jonathanmccracken** [comment]
Closing this.

Was able to work around this using cloudnative-pg's created secrets
```
externalDB:
      enabled: true
      externalDriverType: postgres
      externalConnectionString: 
        valuesFrom:
          secretKeyRef:
            name: mattermost-pgsql-app
            key: uri
```
