### ISSUE TITLE
Bug in mattermost-team-edition readiness probe

### ISSUE THREAD

**Issue by cade-thomas** [mattermost/mattermost-helm#495]
The following readonessProbe does not account for MM_SERVICESETTINGS_CONNECTIONSECURITY: "TLS"
an option should be provided for an https probe to be setup if the user needs. This is a blocker for us at the moment and we would be willing to provide a fix. 

From the deployment template:
```
readinessProbe: {{- .Values.readinessProbe | toYaml | nindent 10 }}
          httpGet:
            path: /api/v4/system/ping
            port: http
```
